"""reg table

Revision ID: 6e9d6074c3c7
Revises: 95400ffd1c94
Create Date: 2021-01-24 00:51:59.298660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9d6074c3c7'
down_revision = '95400ffd1c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration', sa.Column('contact_no', sa.String(length=64), nullable=True))
    op.add_column('registration', sa.Column('username', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registration', 'username')
    op.drop_column('registration', 'contact_no')
    # ### end Alembic commands ###
